apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8suniqueingresshost
metadata:
  name: unique-ingress-host
spec:
  match:
    kinds:
      - apiGroups: ["extensions", "networking.k8s.io"]
        kinds: ["Ingress"]
