apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8sallowedrepos
metadata:
  name: security-repo-is-dtr
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "security"
  parameters:
    repos:
      - "dtr.pac2.demo-azure-cs.mirantis.com"
