kind: Service
apiVersion: v1
metadata:
  name: dockerdemotls
  labels:
    app: dockerdemotls
spec:
  selector:
    app: dockerdemotls
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerdemotls
  labels:
    app: dockerdemotls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerdemotls
  template:
    metadata:
      labels:
        app: dockerdemotls
    spec:
      containers:
      - image: ehazlett/docker-demo:latest
        name: docker-demo-container
        ports:
        - containerPort: 8080
---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: ca-issuer
  name: dockerdemotls
  labels:
    app: dockerdemotls
spec:
  rules:
  - host: dockerdemotls.k8s.pac2.demo-azure-cs.mirantis.com
    http:
      paths:
      - path: /
        backend:
          serviceName: dockerdemotls
          servicePort: 8080
  tls:
  - hosts:
    - dockerdemotls.k8s.pac2.demo-azure-cs.mirantis.com
    secretName: dockerdemotls
