FROM tomcat:8.0-alpine
RUN addgroup -g 1000 -S appgroup && adduser -u 1000 -S appuser -G appgroup
RUN rm -rf /usr/local/tomcat/webapps/*
ADD sample.war /usr/local/tomcat/webapps/
RUN chown -R appuser:appgroup /usr/local/tomcat/webapps/
USER 1000
EXPOSE 8080
CMD ["catalina.sh", "run"]