apiVersion: v1
kind: Pod
metadata:
  name: dropcap
spec:
  containers:
  - name: alpine
    image: dockerpac/alpine:root
    command: [ "/bin/sh", "-c", "sleep 3600" ]
    imagePullPolicy: Always
    securityContext:
      capabilities:
        drop: ["NET_RAW"]
