apiVersion: v1
kind: Pod
metadata:
  name: notroot-psp
spec:
  containers:
  - name: alpine
    image: dockerpac/alpine:notroot
    command: [ "/bin/sh", "-c", "sleep 3600" ]
    imagePullPolicy: Always
