apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-allow-egress-dns
spec:
  policyTypes:
  - Egress
  podSelector: {}
  egress:
  # allow DNS resolution
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
