apiVersion: v1
kind: Pod
metadata:
  name: notrootnotuid
spec:
  containers:
  - name: alpine
    image: dockerpac/alpine:notrootnotuid
    command: [ "/bin/sh", "-c", "sleep 3600" ]
    imagePullPolicy: Always
    securityContext:
      runAsNonRoot: true
