apiVersion: v1
kind: Pod
metadata:
  name: quota
spec:
  containers:
  - name: alpine
    image: dockerpac/alpine:root
    command: [ "/bin/sh", "-c", "sleep 3600" ]
    imagePullPolicy: Always
    volumeMounts:
    - name : test
      mountPath: /test
    resources:
      requests:
        ephemeral-storage: "100Mi"
      limits:
        ephemeral-storage: "100Mi"
  volumes:
  - name: test
    emptyDir: {}
      
    