apiVersion: v1
kind: Pod
metadata:
  name: tomcat
spec:
  initContainers:
  - image: dockerpac/tomcatsample:latest 
    name: webapps
    imagePullPolicy: Always
    command:
      - "cp"
      - "-r"
      - "/usr/local/tomcat/webapps/sample.war"
      - "/webapps/"
    volumeMounts:
    - mountPath: /webapps
      name: webapps
  containers:
  - name: tomcat
    image: dockerpac/tomcatsample:latest
    imagePullPolicy: Always
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    volumeMounts:
    - name: webapps
      mountPath: /usr/local/tomcat/webapps
    - name: work
      mountPath: /usr/local/tomcat/work
    - name: logs
      mountPath: /usr/local/tomcat/logs
  volumes:
  - name: webapps
    emptyDir: {}
  - name: work
    emptyDir: {}
  - name: logs
    emptyDir: {}