server: 
  dev:
      enabled: true
  ingress:
      enabled: true
      hosts:
        - host: vault.k8s.pac2.demo-azure-cs.mirantis.com
          paths: 
            - /
  
  dataStorage:
      enabled: true
      # Size of the PVC created
      size: 5Gi
      # Name of the storage class to use.  If null it will use the
      # configured default Storage Class.
      storageClass: disk
      # Access Mode of the storage device being used for the PVC
      accessMode: ReadWriteOnce